Repository peterdanwan/gimme_readme, pull requests merged in 2024-10, with the labels that each got.

#34 Issue 31 TOML Configuration
  env.sample
  eslint.config.mjs
  package-lock.json
  package.json
  src/_gr.js
  src/ai_config/geminiConfig.js
  src/ai_config/groqConfig.js
  src/file_functions/getTOMLFileValues.js
  src/option_handlers/handleConfigCase.js
  src/option_handlers/handleConfigOption.js
  src/option_handlers/handleFilesOption.js
  tests/unit/file_functions/getConfigFileValues.test.js
Labels: documentation, enhancement

#40 Prompt without any input files and specify prompts within a file
  _examples/prompt-files/prompt-1.txt
  src/_gr.js
  src/commanderProgram.js
  src/option_handlers/handleFilesOption.js
  src/option_handlers/handleNoFilesOption.js
  tests/unit/commanderProgram.test.js
Labels: bug, enhancement

#41 fix(default-prompt): use default prompt if user doesn't use -p or -pf
  src/option_handlers/handleFilesOption.js
  src/option_handlers/handleNoFilesOption.js
Labels: bug
